### ISSUE TITLE
Raise PR to terryspitz

### ISSUE THREAD

**Issue by davidglassborow** [davidglassborow/panbrowserold#1]
@terryspitz I've migrated your PanBrowser code base to work on VS2015, framework v4.5.2, F# 4.
If you want to migrate your original PanBrowser project to Github now Codeplex is being retired (https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/), I'll happily raise a CR to merge my changes back into the original.  

Let me know what you think. 
Cheers, Dave

**Comment by terryspitz** [comment]
Yes please, that's great.

**Comment by davidglassborow** [comment]
Great, if you can follow the instructions in the link above, that will import the project into Github, and then let me know the repos url, and I'll raise a pull request.

**Comment by terryspitz** [comment]
https://github.com/terryspitz/panbrowser
 thanks!

**Comment by davidglassborow** [comment]
https://github.com/terryspitz/panbrowser/pull/1 raised
